package com.ntu.eventbooking.models;

/**
 * Represents a student meet-up event.
 *
 * Events can originate from two sources:
 *   "local"   — created via POST /api/events and stored in Firebase Firestore
 *   "skiddle" — fetched live from the Skiddle public events API and merged into GET /api/events
 *
 * Latitude and longitude are stored to enable:
 *   - Passing location to OpenWeatherMap for live weather data
 *   - Passing location to Skiddle to find nearby public events
 */
public class Event {

    private String eventId;         // auto-generated by Firestore (or Skiddle's own ID)
    private String publisherID;     // student ID of the event creator
    private String title;
    private String type;            // sport / concert / study / gaming / social / other
    private String date;            // ISO format: YYYY-MM-DD
    private String time;            // 24h format: HH:mm  (e.g. "19:00")
    private String venue;           // human-readable venue name (e.g. "NTU Clifton Campus")
    private double cost;            // 0.0 for free events
    private int maxParticipants;
    private int currentAttendees;   // incremented on each successful registration
    private double latitude;        // used for weather lookup and Skiddle proximity search
    private double longitude;
    private double averageRating;   // recalculated on each new rating submission
    private int ratingCount;        // total number of ratings received
    private double ratingTotal;     // sum of all star values — used for exact average recalculation
    private String source;          // "local" or "skiddle"
    private String weather;         // populated at GET /events time from OpenWeatherMap

    public Event() {}

    // ===== Getters and Setters =====

    public String getEventId() { return eventId; }
    public void setEventId(String eventId) { this.eventId = eventId; }

    public String getPublisherID() { return publisherID; }
    public void setPublisherID(String publisherID) { this.publisherID = publisherID; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    public String getDate() { return date; }
    public void setDate(String date) { this.date = date; }

    public String getTime() { return time; }
    public void setTime(String time) { this.time = time; }

    public String getVenue() { return venue; }
    public void setVenue(String venue) { this.venue = venue; }

    public double getCost() { return cost; }
    public void setCost(double cost) { this.cost = cost; }

    public int getMaxParticipants() { return maxParticipants; }
    public void setMaxParticipants(int maxParticipants) { this.maxParticipants = maxParticipants; }

    public int getCurrentAttendees() { return currentAttendees; }
    public void setCurrentAttendees(int currentAttendees) { this.currentAttendees = currentAttendees; }

    public double getLatitude() { return latitude; }
    public void setLatitude(double latitude) { this.latitude = latitude; }

    public double getLongitude() { return longitude; }
    public void setLongitude(double longitude) { this.longitude = longitude; }

    public double getAverageRating() { return averageRating; }
    public void setAverageRating(double averageRating) { this.averageRating = averageRating; }

    public int getRatingCount() { return ratingCount; }
    public void setRatingCount(int ratingCount) { this.ratingCount = ratingCount; }

    public double getRatingTotal() { return ratingTotal; }
    public void setRatingTotal(double ratingTotal) { this.ratingTotal = ratingTotal; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public String getWeather() { return weather; }
    public void setWeather(String weather) { this.weather = weather; }
}
